### ISSUE TITLE
LED ring power usage animation

### ISSUE THREAD

**Issue by lucasvdh** [koktaildotcom/com.p1.smartmeter#13]
A while back I saw this awesome feature at a friends house who has a Homey and a Youless device. 

The Youless Homey app has a LedringAnimation which displays how much power you use by displaying a red overlay on a green background which represents how much power is being used.

I think this should be fairly easy to integrate as it's a nice module which can be extracted and implemented here. The source is at: https://github.com/gruijter/com.gruijter.enelogic/blob/master/ledring.js

**Comment by koktaildotcom** [comment]
I've no intention (for now) to implement this feature
