### ISSUE TITLE
Current power consumption not updated

### ISSUE THREAD

**Issue by koktaildotcom** [koktaildotcom/com.p1.smartmeter#14]
@lucasvdh:
The current power consumption is not updated in the new homey device. The value does update when I run the old p1 reader script.

Haven't done any debugging yet, just noticed this issue. Keeping the old reader running till the issue is fixed. Soonest I'll have some time to debug will prob be next week.

originated from: https://github.com/koktaildotcom/com.p1.smartmeter-dsmr.reader/issues/1

**Comment by koktaildotcom** [comment]
That is not suppose to happen. I don't have the old driver anymore because I've factory reset my development homey unfortunately. Can see in the new driver what data you are missing?

**Comment by pro-sumer** [comment]
I have the same issue when using the new driver.

Apparently you now use (the sum of) `instantaneousConsumedElectricityLx` to calculate the current usage. Unfortunately my smart meter seems to only report `instantaneousConsumedElectricityL1` and always with value `0`.

My fork of your old driver still works fine for my smart meter.

**Comment by pro-sumer** [comment]
I think there's (also) an error in the new script:

https://github.com/koktaildotcom/com.p1.smartmeter-dsmr.reader/issues/1#issuecomment-568208130
