### ISSUE TITLE
Capability "measure_power" (still) shown (on iOS?)

### ISSUE THREAD

**Issue by pro-sumer** [koktaildotcom/com.p1.smartmeter#16]
Capability `measure_power` is shown despite having `"uiCompent": null`.

This happens on iOS (13.3) in Homey App 3.2.0.441.

I experience a similar issue in my own fork of an older version of your App, so this is probably a Homey issue and not yours.

Can other iOS users confirm this issue?

**Comment by koktaildotcom** [comment]
Is this still an issue?

**Comment by pro-sumer** [comment]
That's the one showing as "ENERGIE", right?

(which is a negative number when my solar panels produce more than I consume)

That one I still see.
