### ISSUE TITLE
L1,L2,L3 values still undefined

### ISSUE THREAD

**Issue by JoeryMens** [koktaildotcom/com.p1.smartmeter#36]
Power readings in version 4.0.3 (and before) always were 'NaN'; 
Added locally for all negative/positive L1,L2,L3 values:
`if (isNaN(positiveL1)) {
  positiveL1 = 0
};`

That did solve the problem for me and the app now shows electricity readings.

**Comment by Itsmmai** [comment]
Hi, maybe this is my problem as wel? node answers me with positiveL1 not found.
