### ISSUE TITLE
Homey app shows actual usage as actual produced

### ISSUE THREAD

**Issue by rkokkelk** [koktaildotcom/com.p1.smartmeter#41]
Hi,

First all thanks for the great app. However, when I'm using it, the app shows a negative electricity usage and indicates that I'm actually producing electricity, which is unfortunately not the case.

Manually running the `p1.js` results in the following data and which shows `actualProduced:0` and `actualConsumed: 0.444`. 

```javascript
{ equipmentId: 'E00XXXXXXXXXX121',
  totalConsumed1: 849.545,
  totalConsumed2: 972.065,
  totalProduced1: 0,
  totalProduced2: 0,
  activeTariff: 2,
  actualConsumed: 0.444,
  actualProduced: 0,
  failures: 7,
  failuresLong: 2,
  failureLog: [],
  voltageSagsL1: 0,
  voltageSagsL2: 0,
  voltageSagsL3: 0,
  voltageSwellsL1: 1,
  voltageSwellsL2: 1,
  voltageSwellsL3: 1,
  instantaneousVoltageL1: 239.9,
  instantaneousVoltageL2: 239.1,
  instantaneousVoltageL3: 241.3,
  instantaneousCurrentL1: 1,
  instantaneousCurrentL2: 0,
  instantaneousCurrentL3: 1,
  instantaneousProducedElectricityL1: 0.234,
  instantaneousProducedElectricityL2: 0,
  instantaneousProducedElectricityL3: 0.209,
  instantaneousConsumedElectricityL1: 0,
  instantaneousConsumedElectricityL2: 0,
  instantaneousConsumedElectricityL3: 0 }
  ```

**Comment by rkokkelk** [comment]
Closing issue, because it seems an underlying issue of the DRM reader in the `p1.js` script. As can be seen, my usage is indicated in the:
* `instantaneousProducedElectricityL1`
* `instantaneousProducedElectricityL2`
* `instantaneousProducedElectricityL3`

variables whilst these should be in the `instantaneousConsumedElectricityL*` variables. After looking into the source code of this app `actualConsumed` is never used and can therefore be ignored.

**Comment by koktaildotcom** [comment]
This should be fixed in the last version of https://github.com/koktaildotcom/com.p1.smartmeter-dsmr.reader
