### ISSUE TITLE
User defined capabilities

### ISSUE THREAD

**Issue by lucasvdh** [koktaildotcom/com.p1.smartmeter#8]
# User defined capabilities

## Current situation
You've got one device which displays information on all its capabilities. But in some cases, one or more capabilities might not be relevant for the user.

### Example 1
If a users has a P1 meter which only measures power then the `meter_gas.measure` and `meter_gas.consumed` will always be 0 and irrelevant.

### Example 2
If a user doesn't have solar panels or any other means of generating power then the `measure_power.generated` and `meter_power.generated` will always be 0 and irrelevant.

## Proposal
Add a pairing process in which the user can specify which of the capabilities they want there device to have. My suggestion would be to just display all capabilities with a checkbox before them so the user can choose to enable or disable them for the device that they're adding.

## Code example
When creating a new device (this is done in a pairing view) you can dynamically specify which capabilities it has. For example, something like this:

```javascript
Homey.createDevice({
  name: 'My smart meter',

  capabilities: [
    'measure_power.consumed',
    'meter_power.consumed',
  ],

}, function(err, result) {
  if( err ) return Homey.alert( err );
  Homey.done();
});
```

See [https://apps.developer.athom.com/tutorial-Drivers-Pairing-Custom%20Views.html](https://apps.developer.athom.com/tutorial-Drivers-Pairing-Custom%20Views.html) for more info.

**Comment by hfaas** [comment]
I'd think my situation is very related to this "issue"/"feature-request":
I'd like to add additional examples in which cases a more detailed configuration could benefit:

Besides the fact that I also don't have gas (therefor not interested in it as mentioned above), I also have some solar panels.

I currently can only see what my "consumption" _from the power grid_ is, which is my "actual consumption" minus the "power returned by the solar panels". Homey is currently only show what comes in or out of the power line, so either I'm using or I'm supplying power to the power grid.
 
The meter information provides much more. It is  also provides information about the actual usage of power (regardless of what is being provided by the solar panels). On the other hand it also provides information about the individual return of power by the solar panels.

To get a good grip of the efficiency of a household It would be very useful to be able to split/show al this information separately in Homey as well (or at least be able to configure it).

**Comment by lucasvdh** [comment]
Just noticed you added this in the latest test version, nice work :+1:

**Comment by koktaildotcom** [comment]
> Just noticed you added this in the latest test version, nice work

I've just make it general avaiable. All the credits for the implementation goes to @hfaas! Many thanks for your contribution!
